---
- hosts: all
  gather_facts: yes
  become: true

- name: Configure HAProxy Load Balancer
  hosts: HAproxy
  become: yes

  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: latest

    - name: Configure HAProxy
      file:
        src: haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted


- name: Configure Flask webserver
  hosts: webservers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: install python
      apt:
        name: python3
        state: present

    - name:  install pip3
      apt:
        name: python3-pip
        state: present

    - name: install python3-venv
      apt:
        name: python3-venv
        state: present

    - name: Create flask-app directory
      file:
        path: /home/ubuntu/flask-app
        state: directory

    - name: Change directory to flask-app
      shell: cd /home/ubuntu/flask-app

    - name: Creating virtual environment
      file:
        path: /home/ubuntu/flask-app/venv
        state: directory
        mode: '0755'

    - name: Create VirtualEnv
      pip:
        name: Flask
        virtualenv: /home/ubuntu/flask-app/venv

    - name: permission check
      become: yes
      become_user: root
      file:
        path: /home/ubuntu/flask-app/venv
        mode: '0755'
        recurse: yes

    - name: Installing flask
      shell: pip3 install Flask

    - name: Copy Flask app file
      copy:
        src: dev.py
        dest: /home/ubuntu/flask-app/venv/dev.py

    - name: Run Flask app
      shell:
        cmd: nohup python3 /home/ubuntu/flask-app/venv/dev.py
      async: 5000
      poll: 0    
