---
- hosts: webservers
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: apt update
      apt:
        update_cache: true

    - name: Installing pip3
      apt:
       name: python3-pip
       state: latest
       update_cache: true

    - name: Installing flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: Installing flask services
      apt:
        name: gunicorn

    - name: Copying Flask app
      copy:
        src: /$PWD/app.py
        dest: /home/ubuntu/app.py
        owner: ubuntu
        mode: '0644'

    - name: Running Flask application
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 app:app

# haproxy configuration
- hosts: all
  gather_facts: true
- hosts: HAproxy
  become: true

  tasks:

    - name: apt update
      apt:
        update_cache: yes

    - name: Installing HAPROXY
      apt:
        name: haproxy
        state: present

    - name: Configure haproxy
      template:
        src: /$PWD/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
 
    - name: Check status of haproxy service
      systemd:
        name: haproxy
        state: started
        enabled: true
      register: haproxy_status

    - name: Start haproxy service
      systemd:
        name: haproxy
        state: started
        enabled: true

    - name: Check status of haproxy service using command
      command: systemctl status haproxy.service
      register: haproxy_status

    - name: Check system log for haproxy errors
      shell: journalctl -xe | grep haproxy
      register: haproxy_log
      ignore_errors: true

    - name: Restart haproxy service
      systemd:
        name: haproxy
        state: restarted
