---
  - hosts: all
    become: true
    become_method: sudo
    gather_facts: yes
    tasks:
      - name: apt update
        apt:
          update_cache: yes

  - hosts: webservers
    become: true
    become_method: sudo
    gather_facts: true
    tasks:

       - name: updating
         apt:
           update_cache: true

       - name: Deploying pip3
         apt:
           name: python3-pip
           state: latest
           update_cache: true

       - name: Deploying flask
         pip:
           executable: pip3
           name: flask
           state: latest

       - name: Deploying gunicorn
         apt:
           name: gunicorn

       - name: Copying App.py
         copy:
            src: /$PWD/app.py
            dest: /home/ubuntu/app.py
            owner: ubuntu
            mode: '0644'

       - name: Run Flask application
         shell: gunicorn -w 2 -D -b 0.0.0.0:5000 app:app

       - name: Restart haproxy
         become: true
         service:
            name: haproxy
            state: started
