---
- hosts: webservers
  become: true
  become_method: sudo
  gather_facts: true
  tasks:
    - name: apt update
      apt:
        update_cache: true

    - name: Installing pip3
      apt:
       name: python3-pip
       state: latest
       update_cache: true

    - name: Installing flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: Installing Flask requirements
      apt:
        name: gunicorn

    - name: Copy Flask Applications
      copy:
        src: /$PWD/app.py
        dest: /home/ubuntu/app.py
        owner: ubuntu
        mode: '0644'

    - name: Running Flask application
      shell: gunicorn -w 2 -D -b 0.0.0.0:8080 app:app

# haproxy configuration
- hosts: all
  gather_facts: true
- hosts: HAproxy
  become: true

  tasks:

    - name: apt update
      apt:
        update_cache: yes

    - name: Deploying HAPROXY service to server 
      apt:
        name: haproxy
        state: present

    - name: Configure haproxy
      template:
        src: /$PWD/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
 
    - name: Re-running haproxy
      service:
        name: haproxy
        state: restarted
