---
  - hosts: all
    gather_facts: yes
    become: true

  - hosts: HAproxy
    become: true
    tasks:
      - name: Install HAproxy
        apt:
          name: haproxy
          state: present

      - name: Configure HAproxy
        file:
           src: haproxy.cfg
           dest: /etc/haproxy/haproxy.cfg
        notify: restart haproxy

      - name: Start HAproxy
        systemd:
          name: haproxy
          state: started
          enabled: yes

    handlers:
      - name: Restart HAproxy
        service:
           name: haproxy
           state: restarted

  - hosts: webservers
    become: true
    tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
        
   - name: create Flask directory
     file:
       path: /home/ubuntu/flask_app
       state: directory
       owner: ubuntu
       group: ubuntu

   - name: copy Flask app code
     copy:
       src: dev.py
       dest: /home/ubuntu/flask_app/
       owner: ubuntu
       group: ubuntu

   - name: create virtual environment
     command: python3 -m venv /home/ubuntu/flask_app/venv
     args:
       chdir: /home/ubuntu/flask_app
     register: venv_output

   - name: activate virtual environment
     command: /home/ubuntu/flask_app/venv/bin/activate
     args:
       chdir: /home/ubuntu/flask_app
     environment:
       PATH: "{{ venv_output.stdout_lines[0] }}/bin:{{ ansible_env.PATH }}"

   - name: install Flask in virtual environment
     pip:
       name: Flask
       virtualenv: /home/ubuntu/flask_app/venv
       state: present

   - name: start Flask app
    command: python /home/ubuntu/flask_app/dev.py
     args:
       chdir: /home/ubuntu/flask_app
     environment:
      PATH: "{{ venv_output.stdout_lines[0] }}/bin:{{ ansible_env.PATH }}"
